### ISSUE TITLE
GraphQL API and Backend re-imagination

### ISSUE THREAD

**Issue by sebkasanzew** [TrashRaiders/garbage-collector#172]
Our current backend serving the GraphQL API seems to be to complicated for our needs.

We should rethink our techstack for the backend.

### Use 2 seperate APIs for account-information and business-data

- [x] #178

- account-information is handled by [Prisma](https://www.prisma.io/nextjs) and [PostgreSQL DB](https://www.elephantsql.com/) with [next-auth](https://next-auth.js.org/)
- business-data is handled by GraphQL API (not [Stargate](https://stargate.io/))

**Comment by Sebkasanzew** [comment]
After a discussion between @raphaelzoellner and @Sebkasanzew (me) we decided to go with the 2. option.
